version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node version:"
      - node -v
      - npm -v
      - npm ci

  build:
    commands:
      - npm run build

artifacts:
  base-directory: build
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*
