version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node version:"
      - node -v
      - npm -v
      - npm install

  build:
    commands:
      - npm run build || npm run build:prod || echo "No build script"

artifacts:
  files:
    - '**/*'
  base-directory: build